### ISSUE TITLE
Invalid apiVersion

### ISSUE THREAD

**Issue by federeynimbux** [nimbux911/terraform-aws-eks#12]
The following error is displayed when trying to perform a `terraform plan`.

`Error: Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`

Searching for the error and deleting helm elements, it was found that the helm provider used the api

`client.authentication.k8s.io/v1alpha1`

As the helm provider version was not fixed, we updated to the latest version and stopped using that api.

**Comment by qemanuel** [comment]
Fixed on https://github.com/nimbux911/terraform-aws-eks/releases/tag/v3.1.5 , thanks !
