### ISSUE TITLE
Consider Open-Sourcing the project by adding a License

### ISSUE THREAD

**Issue by asajaroff** [nimbux911/terraform-aws-eks#9]
First of all nice work! 
The module looks pretty complete and well thought out. 

Please consider using license by adding a file called `LICENSE` at the root of the repository directory 😉.

**Comment by federicoaaguirre** [comment]
Hi Alejandro, thanks for the suggestion, we will do it 🦾. Also be free to contribute.!

**Comment by ivours** [comment]
Thanks @asajaroff for contributing!

@federicoaaguirre, I've left some comments in #10.

**Comment by federicoaaguirre** [comment]
Solved: [v3.1.4](https://github.com/nimbux911/terraform-aws-eks/releases/tag/v3.1.4)
